name: survivor_test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.10.4
  flutter: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.33.0
  flame_tiled: ^3.0.9

flutter:
  assets:
    - assets/images/
    - assets/images/HUD/
    - assets/images/Items/Fruits/
    - assets/images/Terrain/
    - assets/images/Terrain/summer/
    - assets/images/Terrain/winter/
    - assets/images/Terrain/autumn/
    - assets/images/Traps/Saw/
    - assets/audio/
    - assets/tiles/